action_id: trunk-single-player-auto-upgrade
date: 2026-04-22 10:14:02
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1776852842
full_timestamp:
  nanos: 804271000
  seconds: 1776852842
trunk_version: 1.25.0
