action_id: trunk-cache-prune
date: 2026-04-19 09:15:09
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1776590109
full_timestamp:
  nanos: 810718000
  seconds: 1776590109
trunk_version: 1.25.0
