action_id: trunk-cache-prune
date: 2026-04-22 09:03:35
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1776848615
full_timestamp:
  nanos: 785007000
  seconds: 1776848615
trunk_version: 1.25.0
