@echo off
REM Generated by trunk tool 'checkov'
set PATH=C:\Users\nasee\AppData\Local\trunk\tools\checkov\3.2.521-3adf90f2e186ddf3af35d1baa7a5d166/bin;C:\Users\nasee\AppData\Local\trunk\tools\checkov\3.2.521-3adf90f2e186ddf3af35d1baa7a5d166/Scripts;C:\Users\nasee\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\nasee\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\nasee\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\nasee\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\nasee\AppData\Local\trunk\tools\checkov\3.2.521-3adf90f2e186ddf3af35d1baa7a5d166

start /w /b checkov %*
