@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\nasee\AppData\Local\trunk\tools\osv-scanner\2.3.5-d0250432765437a8b2c2f5b425200853;C:\Users\nasee\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\nasee\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
