@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\nasee\AppData\Local\trunk\tools\trufflehog\3.94.3-8d48f61231211cd534bd0c25db4f4f12;C:\Users\nasee\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\nasee\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
