action_id: trunk-share-with-everyone
date: 2026-04-17 01:42:41
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1776390161
full_timestamp:
  nanos: 526459000
  seconds: 1776390161
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
